### ISSUE TITLE
TTL issue - value needs to be in seconds not minutes

### ISSUE THREAD

**Issue by techhitnz** [alphabt/asuswrt-merlin-ddns-cloudflare#1]
TTL is in seconds and not minutes.  And the minimum TTL is 2 hours (7200 seconds) or else the API will reject it.

This script was erroring without any error messages until I started debugging with manual values, where I could finally see what the issue was.  I suspect the API might've changed the TTL from seconds to minutes recently, as I had this same script going without any issue earlier this year.

**Comment by alphabt** [comment]
Thanks for reporting this. It’s probably my mistake since DNS TTL is almost
always denoted in seconds. I’ll fix the comment in the code.

**Comment by alphabt** [comment]
Fixed with https://github.com/alphabt/asuswrt-merlin-ddns-cloudflare/commit/a689e75b0781f3e21c5ae6d5e35c00fefafe0eb5.

**Comment by techhitnz** [comment]
Auto TTL value of "1" does not work. I haven't tried with many values but "1" (your default) does not work. The response returned says the minimum value needs to be 2 hours (7200 seconds)

**Comment by alphabt** [comment]
@techhitnz Sorry I couldn't repro your issue. I manually ran the command it worked for me with TTL set to 1. Here's what I ran:

```shell
$ curl -s -X PUT "https://api.cloudflare.com/client/v4/zones/<snipped>/dns_records/<snipped>" \
  -H "Content-Type: application/json" \
  -H "X-Auth-Email: <snipped>" \
  -H "X-Auth-Key: <snipped>" \
  --data '{"type":"A","name":"<snipped>","content":"<snipped>","ttl":1,"proxied":false}'
```
```json
{
  "result": {
    "id": "<snipped>",
    "type": "A",
    "name": "<snipped>",
    "content": "<snipped>",
    "proxiable": true,
    "proxied": false,
    "ttl": 1,
    "locked": false,
    "zone_id": "<snipped>",
    "zone_name": "<snipped>",
    "modified_on": "2019-06-17T19:05:09.376017Z",
    "created_on": "2019-06-17T19:05:09.376017Z",
    "meta": {
      "auto_added": false,
      "managed_by_apps": false,
      "managed_by_argo_tunnel": false
    }
  },
  "success": true,
  "errors": [],
  "messages": []
}
```

Could you try manually running the command by hand?

**Comment by techhitnz** [comment]
You're right.  Sorry.
