### ISSUE TITLE
This script requires python to be installed?

### ISSUE THREAD

**Issue by maidmeow4** [alphabt/asuswrt-merlin-ddns-cloudflare#5]
Then why it is not described in the `README` file?

_Just wasted serval hours to debug this script_

**Comment by alphabt** [comment]
You're right it should've been called out in `README`. I've added a note via https://github.com/alphabt/asuswrt-merlin-ddns-cloudflare/commit/a288696bdd8b55b7938abbcc15783e0cfb09885c. Thanks for calling this out!
