### ISSUE TITLE
script turns off proxy on cloudflare domain

### ISSUE THREAD

**Issue by packrobottom** [alphabt/asuswrt-merlin-ddns-cloudflare#9]
correctly updates a record but turns off proxied to dns only

**Comment by alphabt** [comment]
Hi @packrobottom, thanks for reporting this issue. I am no longer using this script to update my own DDNS since there's a new way to do that at https://github.com/RMerl/asuswrt-merlin.ng/wiki/DDNS-services. But feel free to create a pull request and I'll be happy to merge it in.

**Comment by packrobottom** [comment]
I’ve just decided to write a script myself.  Works well updates multiple domains at once just place it in /jjfs/scripts/dhcpc-event
And it will auto update on ip change

#!/bin/sh
#cloudflare script to update multiple A records on ip change
#requires entware,jq and dig installed

export PATH="$PATH:/opt/bin"

sleep 120

token="Replace with api token"
ip="$(dig +short myip.opendns.com @resolver1.opendns.com)"

get_record_id() {
    curl -fsL -X GET "https://api.cloudflare.com/client/v4/zones/$1/dns_records?type=A&name=$2" \
        -H "Authorization: Bearer $token" \
        -H "Content-Type: application/json" | jq -r .result[].id
}

update() {
    [ "$4" = "direct" ] && proxied="false" || proxied="true"
    curl -L -X PATCH "https://api.cloudflare.com/client/v4/zones/$1/dns_records/$(get_record_id $1 $2)" \
        -H "Authorization: Bearer $token" \
        -H "Content-Type: application/json" \
        --data "{\"type\":\"A\",\"name\":\"$2\",\"content\":\"$3\",\"ttl\":120,\"proxied\":$proxied}"
}

# usage: update <zone_id> <record name> <ip> [direct] 

update ZoneID  example1.com $ip
update ZoneID  example2.com $ip direct
update ZoneID  sub.example2.com $ip

#Log the event
logger DHCPC-EVENT SCRIPT: CloudFlare has been updated to $ip

**Comment by alphabt** [comment]
That's great! I'm glad you were able to get it working 😄
